/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import Control.DetailPerjalananControl;
import Model.DetailPerjalanan;
import Model.Member;
import Model.StatusType;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JComponent;
import Control.*;
import Model.Kendaraan;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class BookFlightPanel extends javax.swing.JPanel {
    private Member member;
    private DetailPerjalananControl dPCon = new DetailPerjalananControl();
    private KendaraanControl kCon = new KendaraanControl();
    public void setMember(Member member){
        this.member = member;
    }
    
    public BookFlightPanel(Member member) {
        setMember(member);
        initComponents();
        List<DetailPerjalanan> listDp = dPCon.showAllDetailPerjalanan();  
        List<DetailPerjalanan> tempList = new ArrayList();
        List<Kendaraan> listK = kCon.showAllDataKendaraan();
        List<String> listKeberangkatan = new ArrayList();
        List<String> listKedatangan = new ArrayList();
        for(DetailPerjalanan dP : listDp){
            tanggalKeberangkatanCb.addItem(dP.getTanggalKeberangkatan());
            listKeberangkatan.add(dP.getKotaKeberangkatan());
            listKedatangan.add(dP.getKotaKedatangan());
        }

        for(int i = 0; i<listKeberangkatan.size();i++){
            for(int j = i+1 ; j<listKeberangkatan.size() ; j++){
                System.out.println("list ... " + listKeberangkatan.get(i) + " bandingkan " + listKeberangkatan.get(j));
                if(listKeberangkatan.get(i).equalsIgnoreCase(listKeberangkatan.get(j))){
                    System.out.println("masuk");
                    listKeberangkatan.remove(j);
                }
            }
       }
        for(int i = 0; i<listKedatangan.size();i++){
            for(int j = i+1 ; j<listKedatangan.size() ; j++){
                if(listKedatangan.get(i).equalsIgnoreCase(listKedatangan.get(j))){
                    listKedatangan.remove(j);
                }
            }
       }
        
        for(int i =0;i<listKeberangkatan.size();i++){
            kotaKeberangkatanCb.addItem(listKeberangkatan.get(i));
            
        }
        for(int i =0;i<listKedatangan.size();i++){
            
            kotaTujuanCb.addItem(listKedatangan.get(i));
        }
 
        findPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setForm(new FlightPanel(member,kotaKeberangkatanCb.getSelectedItem().toString(),
                        kotaTujuanCb.getSelectedItem().toString(),
                        tanggalKeberangkatanCb.getSelectedItem().toString(),
                        Integer.parseInt(jumlahPenumpangInput.getText()))
                );   
            }
        });
        
        cariLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(Integer.parseInt(jumlahPenumpangInput.getText()) > 10 || Integer.parseInt(jumlahPenumpangInput.getText())<=0){
                    JOptionPane.showMessageDialog(mainPanel, "Jumlah Penumpang Minimal 1 dan Maksimal 10!!!");
                } else if (jumlahPenumpangInput.getText().isBlank()){
                    JOptionPane.showMessageDialog(mainPanel, "Jumlah Penumpang Harus Di Input!!!");
                }else {
                    setForm(new FlightPanel(member,kotaKeberangkatanCb.getSelectedItem().toString(),
                        kotaTujuanCb.getSelectedItem().toString(),
                        tanggalKeberangkatanCb.getSelectedItem().toString(),
                        Integer.parseInt(jumlahPenumpangInput.getText()))
                     ); 
                }
            }
        });
    }

    private void setForm(JComponent com){
        mainPanel.removeAll();
        mainPanel.setLayout(new CardLayout());
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new Panel.PanelBorder();
        jumlahPenumpangInput = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameLabel2 = new javax.swing.JLabel();
        usernameLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        findPanel = new Panel.PanelBorder();
        cariLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jumlahPenumpangLbl = new javax.swing.JLabel();
        kotaTujuanCb = new javax.swing.JComboBox<>();
        tanggalKeberangkatanCb = new javax.swing.JComboBox<>();
        kotaKeberangkatanCb = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jumlahPenumpangInput.setBackground(new java.awt.Color(255, 255, 255, 80));
        jumlahPenumpangInput.setForeground(new java.awt.Color(0, 0, 0));
        jumlahPenumpangInput.setText("Maks 10 Orang");
        jumlahPenumpangInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jumlahPenumpangInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jumlahPenumpangInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jumlahPenumpangInputFocusLost(evt);
            }
        });
        jumlahPenumpangInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jumlahPenumpangInputMouseEntered(evt);
            }
        });
        jumlahPenumpangInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahPenumpangInputActionPerformed(evt);
            }
        });

        usernameLabel.setText("Tanggal Keberangkatan");

        usernameLabel2.setText("Kota Keberangkatan");

        usernameLabel3.setText("Kota Tujuan");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plane.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Choose your tickets");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ayo, jangan lewatkan kesempatan untuk membeli tiket");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("dan bergabung dalam pengalaman luar biasa yang akan membuatmu terpesona!");

        findPanel.setBackground(new java.awt.Color(0, 153, 153));
        findPanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        findPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                findPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                findPanelMouseExited(evt);
            }
        });

        cariLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cariLbl.setForeground(new java.awt.Color(255, 255, 255));
        cariLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cariLbl.setText("Cari Tiket");
        cariLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cariLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cariLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout findPanelLayout = new javax.swing.GroupLayout(findPanel);
        findPanel.setLayout(findPanelLayout);
        findPanelLayout.setHorizontalGroup(
            findPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(cariLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        findPanelLayout.setVerticalGroup(
            findPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cariLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(153, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/header.png"))); // NOI18N

        jumlahPenumpangLbl.setText("Jumlah Penumpang");

        kotaTujuanCb.setBackground(new java.awt.Color(255, 255, 255));
        kotaTujuanCb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kotaTujuanCb.setForeground(new java.awt.Color(0, 0, 0));
        kotaTujuanCb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tanggalKeberangkatanCb.setBackground(new java.awt.Color(255, 255, 255));
        tanggalKeberangkatanCb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tanggalKeberangkatanCb.setForeground(new java.awt.Color(0, 0, 0));
        tanggalKeberangkatanCb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        kotaKeberangkatanCb.setBackground(new java.awt.Color(255, 255, 255));
        kotaKeberangkatanCb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kotaKeberangkatanCb.setForeground(new java.awt.Color(0, 0, 0));
        kotaKeberangkatanCb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggalKeberangkatanCb, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlahPenumpangLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlahPenumpangInput, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kotaTujuanCb, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kotaKeberangkatanCb, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(findPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(37, 37, 37)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahPenumpangLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaKeberangkatanCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalKeberangkatanCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahPenumpangInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(usernameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(findPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kotaTujuanCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahPenumpangInputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahPenumpangInputMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahPenumpangInputMouseEntered

    private void jumlahPenumpangInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahPenumpangInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahPenumpangInputActionPerformed

    private void findPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPanelMouseEntered
        findPanel.setBackground(new Color(0,102,102));
        findPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_findPanelMouseEntered

    private void findPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPanelMouseExited
        findPanel.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_findPanelMouseExited

    private void jumlahPenumpangInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlahPenumpangInputFocusGained
        String temp = jumlahPenumpangInput.getText();
        
        if(temp.equals("Maks 10 Orang")){
            jumlahPenumpangInput.setText("");
        }else{
            jumlahPenumpangInput.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jumlahPenumpangInputFocusGained

    private void jumlahPenumpangInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlahPenumpangInputFocusLost
        String temp = jumlahPenumpangInput.getText();
        
        
        if(temp.equals("") || temp.equals("Maks 10 Orang")){
            jumlahPenumpangInput.setText("Maks 10 Orang");
        }else{
            jumlahPenumpangInput.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jumlahPenumpangInputFocusLost

    private void findPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPanelMouseClicked
        // Kalau klik cari tiket
        
        
        
        
    }//GEN-LAST:event_findPanelMouseClicked

    private void cariLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariLblMouseClicked
        // ntar copas code label dan ganti variabelnya
    }//GEN-LAST:event_cariLblMouseClicked

    private void cariLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariLblMouseEntered
        cariLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        findPanel.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_cariLblMouseEntered

    private void cariLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariLblMouseExited
        findPanel.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_cariLblMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cariLbl;
    private Panel.PanelBorder findPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlahPenumpangInput;
    private javax.swing.JLabel jumlahPenumpangLbl;
    private javax.swing.JComboBox<String> kotaKeberangkatanCb;
    private javax.swing.JComboBox<String> kotaTujuanCb;
    private Panel.PanelBorder mainPanel;
    private javax.swing.JComboBox<String> tanggalKeberangkatanCb;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel2;
    private javax.swing.JLabel usernameLabel3;
    // End of variables declaration//GEN-END:variables
}
