/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import Control.*;
import Model.StatusType;
import Model.*;
import java.awt.Color;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;



public class DataTicketPanel extends javax.swing.JPanel {
    private int pemesananID;
    private TiketControl tCon = new TiketControl();
    private DetailPerjalananControl dpCon;
    private KendaraanControl kCon = new KendaraanControl();   
    
    public void setPemesananID(int pemesananID){
        this.pemesananID = pemesananID;
    }
    
    public DataTicketPanel(int pemesananID) {
        dpCon = new DetailPerjalananControl();
        
        
        initComponents();
        init();
        setPemesananID(pemesananID);      
        List<Tiket> listT = tCon.showDataTiketPesanan(pemesananID);
        System.out.println("MASUK   1");
        System.out.println("testttttttttt : " + listT.get(0).getdetailPerjalanan().getDetailPerjalanId());
        DetailPerjalanan DP = dpCon.showDetailPerjalanan(listT.get(0).getdetailPerjalanan().getDetailPerjalanId());
        System.out.println("hahahah kota keberangkatan : " + DP.getKotaKeberangkatan()); // ini dapat
        System.out.println("hahahha id kendaraan : " + DP.getKendaraan().getKendaraanID()); // ini gk dapat
        System.out.println("MASUK   2");
        
        Kendaraan K = kCon.searchKendaraan(DP.getKendaraan().getKendaraanID());
        System.out.println("MASUK   3");
        setComponent(listT, DP, K);
            for(Tiket tK : listT){          
                tablePesanan.addRow(new Object[]{tK.getTiketId(), tK.getDataPelanggan().getNamaPemesan(),tK.getDataPelanggan().getIdCard(), tK.getNomorSeat(), tK.getDataPelanggan().getKewarganegaraan()});
            }
        }
    
    public void setComponent(List<Tiket> listT, DetailPerjalanan DP, Kendaraan K){
        System.out.println("MASUK   4");
        namaKendaraanLbl.setText(K.getNamaKendaraan());
        jenisKendaraanLbl.setText(K.getJenisKendaraan());
        kotaKeberangkatanLbl.setText(DP.getKotaKeberangkatan());
        kotaTujuanLbl.setText(DP.getKotaKedatangan());
        jamKeberangkatanLbl.setText(DP.getWaktuKeberangkatan());
        jamKedatanganLbl.setText(DP.getWaktuKedatangan());
        tanggalKeberangkatanLbl.setText(DP.getTanggalKeberangkatan());
        tanggalKedatanganLbl.setText(DP.getTanggalKedatangan());
        nomorKeberangkatanLbl.setText(DP.getNomorKeberangkatan());
    }
    
    public void init(){
        
        JPanel panel = new JPanel();
        panel.setBackground(Color.WHITE);
       
        sp2.setVerticalScrollBar(new ScrollBar.ScrollBarCustom());
        sp2.getVerticalScrollBar().setBackground(Color.WHITE);
        sp2.setCorner(JScrollPane.UPPER_RIGHT_CORNER, panel);
        sp2.getViewport().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticketLbl = new Panel.PanelBorder();
        headerLbl = new javax.swing.JLabel();
        descLbl = new javax.swing.JLabel();
        panelBorder1 = new Panel.PanelBorder();
        namaKendaraanLbl = new javax.swing.JLabel();
        jenisKendaraanLbl = new javax.swing.JLabel();
        nomorKeberangkatanLbl = new javax.swing.JLabel();
        kotaTujuanLbl = new javax.swing.JLabel();
        kotaKeberangkatanLbl = new javax.swing.JLabel();
        tanggalKedatanganLbl = new javax.swing.JLabel();
        tanggalKeberangkatanLbl = new javax.swing.JLabel();
        jamKedatanganLbl = new javax.swing.JLabel();
        jamKeberangkatanLbl = new javax.swing.JLabel();
        iconLbl = new javax.swing.JLabel();
        bookinIdBoldLbl = new javax.swing.JLabel();
        bookingIdChildLbl = new javax.swing.JLabel();
        stripeLbl = new javax.swing.JLabel();
        sp2 = new javax.swing.JScrollPane();
        tablePesanan = new Table.Table();

        setBackground(new java.awt.Color(255, 255, 255));

        ticketLbl.setBackground(new java.awt.Color(255, 255, 255));
        ticketLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        headerLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headerLbl.setForeground(new java.awt.Color(0, 0, 0));
        headerLbl.setText("E-Ticket");

        descLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descLbl.setForeground(new java.awt.Color(0, 0, 0));
        descLbl.setText("Detail Penerbangan");

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        namaKendaraanLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namaKendaraanLbl.setForeground(new java.awt.Color(0, 0, 0));
        namaKendaraanLbl.setText("Nama Kendaraan");

        jenisKendaraanLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jenisKendaraanLbl.setForeground(new java.awt.Color(0, 0, 0));
        jenisKendaraanLbl.setText("Jenis Kendaraan");

        nomorKeberangkatanLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomorKeberangkatanLbl.setForeground(new java.awt.Color(0, 0, 0));
        nomorKeberangkatanLbl.setText("Nomor Keberangkatan");

        kotaTujuanLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kotaTujuanLbl.setForeground(new java.awt.Color(0, 0, 0));
        kotaTujuanLbl.setText("Kota Tujuan");

        kotaKeberangkatanLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kotaKeberangkatanLbl.setForeground(new java.awt.Color(0, 0, 0));
        kotaKeberangkatanLbl.setText("Kota Keberangkatan");

        tanggalKedatanganLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tanggalKedatanganLbl.setForeground(new java.awt.Color(0, 0, 0));
        tanggalKedatanganLbl.setText("\"");

        tanggalKeberangkatanLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tanggalKeberangkatanLbl.setForeground(new java.awt.Color(0, 0, 0));
        tanggalKeberangkatanLbl.setText("\"");

        jamKedatanganLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jamKedatanganLbl.setForeground(new java.awt.Color(0, 0, 0));
        jamKedatanganLbl.setText("20.30");

        jamKeberangkatanLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jamKeberangkatanLbl.setForeground(new java.awt.Color(0, 0, 0));
        jamKeberangkatanLbl.setText("19.00");

        iconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/e-Ticket.png"))); // NOI18N

        bookinIdBoldLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookinIdBoldLbl.setForeground(new java.awt.Color(0, 0, 0));
        bookinIdBoldLbl.setText("TIKETA Booking ID");

        bookingIdChildLbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bookingIdChildLbl.setText("Booking ID");

        stripeLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stripeLbl.setForeground(new java.awt.Color(0, 0, 0));
        stripeLbl.setText("-");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jenisKendaraanLbl)
                        .addGap(6, 6, 6))
                    .addComponent(namaKendaraanLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addComponent(jamKeberangkatanLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addComponent(jamKedatanganLbl)
                        .addGap(3, 3, 3)))
                .addComponent(iconLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(kotaKeberangkatanLbl)
                        .addGap(48, 48, 48)
                        .addComponent(tanggalKeberangkatanLbl)
                        .addGap(8, 8, 8)
                        .addComponent(stripeLbl)
                        .addGap(5, 5, 5)
                        .addComponent(tanggalKedatanganLbl))
                    .addComponent(kotaTujuanLbl))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookinIdBoldLbl)
                    .addComponent(nomorKeberangkatanLbl)
                    .addComponent(bookingIdChildLbl))
                .addGap(47, 47, 47))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(namaKendaraanLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisKendaraanLbl)
                .addGap(37, 37, 37))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(bookinIdBoldLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookingIdChildLbl)
                        .addGap(3, 3, 3)
                        .addComponent(nomorKeberangkatanLbl))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanggalKeberangkatanLbl)
                            .addComponent(tanggalKedatanganLbl)
                            .addComponent(stripeLbl))
                        .addGap(28, 28, 28)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jamKedatanganLbl))
                            .addComponent(iconLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jamKeberangkatanLbl))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(kotaKeberangkatanLbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kotaTujuanLbl)
                        .addGap(19, 19, 19))))
        );

        sp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablePesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Ticket", "Name", "ID Card", "Seat", "Nationality"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sp2.setViewportView(tablePesanan);

        javax.swing.GroupLayout ticketLblLayout = new javax.swing.GroupLayout(ticketLbl);
        ticketLbl.setLayout(ticketLblLayout);
        ticketLblLayout.setHorizontalGroup(
            ticketLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketLblLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ticketLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketLblLayout.createSequentialGroup()
                        .addGroup(ticketLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descLbl)
                            .addComponent(headerLbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ticketLblLayout.createSequentialGroup()
                        .addGroup(ticketLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp2))
                        .addContainerGap())))
        );
        ticketLblLayout.setVerticalGroup(
            ticketLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketLblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLbl)
                .addGap(18, 18, 18)
                .addComponent(descLbl)
                .addGap(32, 32, 32)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ticketLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookinIdBoldLbl;
    private javax.swing.JLabel bookingIdChildLbl;
    private javax.swing.JLabel descLbl;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel iconLbl;
    private javax.swing.JLabel jamKeberangkatanLbl;
    private javax.swing.JLabel jamKedatanganLbl;
    private javax.swing.JLabel jenisKendaraanLbl;
    private javax.swing.JLabel kotaKeberangkatanLbl;
    private javax.swing.JLabel kotaTujuanLbl;
    private javax.swing.JLabel namaKendaraanLbl;
    private javax.swing.JLabel nomorKeberangkatanLbl;
    private Panel.PanelBorder panelBorder1;
    private javax.swing.JScrollPane sp2;
    private javax.swing.JLabel stripeLbl;
    private Table.Table tablePesanan;
    private javax.swing.JLabel tanggalKeberangkatanLbl;
    private javax.swing.JLabel tanggalKedatanganLbl;
    private Panel.PanelBorder ticketLbl;
    // End of variables declaration//GEN-END:variables
}
