
package Panel;

import Model.Member;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

public class DepositPanel extends javax.swing.JPanel {

    private Member member;
 
    public void setMember(Member member){
        saldoLbl.setText(Double.toString(member.getTwallet().getSaldo()));
        this.member = member;
    }
    
    public DepositPanel(Member member) {
        initComponents();
        setMember(member);
        String action = "deposit";

            sendBtn.addMouseListener(new MouseAdapter() {
                    @Override                
                    public void mouseClicked(MouseEvent e) {
                        if(Double.parseDouble(jmlDepoInput.getText()) < 10000){
                            JOptionPane.showMessageDialog(mainPanel, "Jumlah Deposit Tidak Boleh Kurang Dari Rp.10.000,- !!!");
                        } else {
                            setForm(new SuccessPaymentPanel(member,action,Double.parseDouble(jmlDepoInput.getText())));
                        }
                    }
                });
        }
    
    private void setForm(JComponent com){
        mainPanel.removeAll();
        mainPanel.setLayout(new CardLayout());
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jmlDepoInput = new javax.swing.JTextField();
        depoLbl = new javax.swing.JLabel();
        metodComboBox = new javax.swing.JComboBox<>();
        metodLbl = new javax.swing.JLabel();
        sendBtn = new rojerusan.RSMaterialButtonRectangle();
        logoPanel = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        headerHistory1 = new Panel.HeaderHistory();
        moneyIcon = new javax.swing.JLabel();
        rpLbl = new javax.swing.JLabel();
        saldoLbl = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jmlDepoInput.setBackground(new java.awt.Color(255, 255, 255, 80));
        jmlDepoInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jmlDepoInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmlDepoInputMouseEntered(evt);
            }
        });
        jmlDepoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlDepoInputActionPerformed(evt);
            }
        });

        depoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        depoLbl.setForeground(new java.awt.Color(0, 0, 0));
        depoLbl.setText("Masukkan Jumlah Deposit");

        metodComboBox.setBackground(new java.awt.Color(255, 255, 255));
        metodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dana", "Ovo", "Gopay", "BCA", "BRI", "Mandiri" }));

        metodLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        metodLbl.setForeground(new java.awt.Color(0, 0, 0));
        metodLbl.setText("Pilih Metode");

        sendBtn.setText("Send");
        sendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendBtnMouseEntered(evt);
            }
        });
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        logoPanel.setBackground(new java.awt.Color(255, 255, 255));

        logoIcon.setBackground(new java.awt.Color(255, 255, 255));
        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/allMoneyIcon.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        moneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Money.png"))); // NOI18N

        rpLbl.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        rpLbl.setForeground(new java.awt.Color(255, 255, 255));
        rpLbl.setText("Rp");

        saldoLbl.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        saldoLbl.setForeground(new java.awt.Color(255, 255, 255));
        saldoLbl.setText("Saldo Anda");

        javax.swing.GroupLayout headerHistory1Layout = new javax.swing.GroupLayout(headerHistory1);
        headerHistory1.setLayout(headerHistory1Layout);
        headerHistory1Layout.setHorizontalGroup(
            headerHistory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerHistory1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(moneyIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rpLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldoLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerHistory1Layout.setVerticalGroup(
            headerHistory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerHistory1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(headerHistory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerHistory1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(headerHistory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoLbl)
                            .addComponent(rpLbl))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depoLbl)
                    .addComponent(jmlDepoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metodLbl)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerHistory1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(depoLbl)
                        .addGap(18, 18, 18)
                        .addComponent(jmlDepoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(metodLbl)
                        .addGap(18, 18, 18)
                        .addComponent(metodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jmlDepoInputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmlDepoInputMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlDepoInputMouseEntered

    private void jmlDepoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlDepoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlDepoInputActionPerformed

    private void sendBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBtnMouseClicked
          
    }//GEN-LAST:event_sendBtnMouseClicked

    private void sendBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sendBtnMouseEntered

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed

    }//GEN-LAST:event_sendBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel depoLbl;
    private Panel.HeaderHistory headerHistory1;
    private javax.swing.JTextField jmlDepoInput;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> metodComboBox;
    private javax.swing.JLabel metodLbl;
    private javax.swing.JLabel moneyIcon;
    private javax.swing.JLabel rpLbl;
    private javax.swing.JLabel saldoLbl;
    private rojerusan.RSMaterialButtonRectangle sendBtn;
    // End of variables declaration//GEN-END:variables
}
