/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author USER
 */
public class HeaderHistory extends javax.swing.JPanel {

    /**
     * Creates new form headerHistory
     */
    public HeaderHistory() {
        initComponents();
        setOpaque(false);
    }
    
    protected void paintComponent(Graphics g) {
        Graphics2D g3;
        Graphics2D g2 =(Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g3= g2;
        g2.setColor(new Color(0,91,110));
        g3.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g3.setColor(new Color(255,255,255,80));
        g3.fillOval(getWidth()-(getHeight()/2), 10, getHeight(), getHeight());
        g3.fillOval(10 - (getHeight()/2), 10, getHeight(), getHeight());
        g3.fillOval(50 - (getHeight()/2)-20, getHeight()/2 + 20, getHeight(), getHeight());
        g3.fillOval(getWidth()-(getHeight()/2)-20, getHeight()/2 + 20, getHeight(), getHeight());
        super.paintComponent(g); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
