/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;
//import view.*;
import View.LoginView;
import java.awt.Font;
import javax.swing.SwingUtilities;

/**
 *
 * @author USER
 */
public class LogOutPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogOutPanel
     */
    public LogOutPanel() {
        initComponents();
        //LoginView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        leftSidePanel = new javax.swing.JPanel();
        headText = new javax.swing.JLabel();
        descText = new javax.swing.JLabel();
        descText2 = new javax.swing.JLabel();
        descText3 = new javax.swing.JLabel();
        headText2 = new javax.swing.JLabel();
        logoutBtn = new rojerusan.RSMaterialButtonRectangle();

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setOpaque(false);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/LogoutImage.png"))); // NOI18N

        leftSidePanel.setBackground(new java.awt.Color(255, 255, 255));

        headText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headText.setForeground(new java.awt.Color(0, 0, 0));
        headText.setText("Book Flight Tickets");

        descText.setForeground(new java.awt.Color(0, 0, 0));
        descText.setText("We're grateful for the opportunity to serve you");

        descText2.setForeground(new java.awt.Color(0, 0, 0));
        descText2.setText("through our ticketing application. We value your support and");

        descText3.setForeground(new java.awt.Color(0, 0, 0));
        descText3.setText("hope to continue being your go-to platform for future events.");

        headText2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headText2.setForeground(new java.awt.Color(0, 0, 0));
        headText2.setText("With Tiketa!");

        logoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        logoutBtn.setText("Logout");
        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftSidePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descText3)
                            .addComponent(descText2)
                            .addComponent(descText)
                            .addComponent(headText)
                            .addComponent(headText2)))
                    .addGroup(leftSidePanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headText)
                .addGap(12, 12, 12)
                .addComponent(headText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descText3)
                .addGap(28, 28, 28)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        // ke login view
        //LoginView();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        //LoginView();
           LoginView lv = new LoginView();
           this.setEnabled(true);
           lv.setVisible(true); 
           SwingUtilities.getWindowAncestor(logoutBtn).dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel descText;
    private javax.swing.JLabel descText2;
    private javax.swing.JLabel descText3;
    private javax.swing.JLabel headText;
    private javax.swing.JLabel headText2;
    private javax.swing.JLabel image;
    private javax.swing.JPanel leftSidePanel;
    private rojerusan.RSMaterialButtonRectangle logoutBtn;
    // End of variables declaration//GEN-END:variables
}
