/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import Model.*;
import Control.*;
import Exception.NotEnoughMoneyException;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class PaymentPanel extends javax.swing.JPanel {
    TWalletControl twCon = new TWalletControl();
    TransaksiControl tCon = new TransaksiControl();
    SeatControl sCon = new SeatControl();
    private Member m;
    private Pemesanan p;
    
    public void setPemesanan(Pemesanan p){
        this.p = p;
    }
    
    public void setMember(Member m){
        this.m = m;
    }
    
   
    public void NotEnoughMoneyException() throws NotEnoughMoneyException{
        if(p.getTotalTagihan() + (p.getJumlahPesanan()*2500)+ (p.getTotalTagihan()*0.1) > m.getTwallet().getSaldo()){
            throw new NotEnoughMoneyException("Uang tidak Cukup!");
        }
    }
    
    public PaymentPanel(Member m,Pemesanan p) {
        JPanel paymentPanel = new JPanel();
        initComponents();
        setPemesanan(p);
        setMember(m);
        init();
        System.out.println("Jumlah Tiket : " + p.getTiket().size());
        for(Tiket t : p.getTiket()){
            tablePenumpang.addRow(new Object[]{t.getDataPelanggan().getNamaPemesan(),
                sCon.showSeat(t.getNomorSeat(),t.getdetailPerjalanan().getDetailPerjalanId()).getKelas().getJenisKelas(),
                t.getNomorSeat(),
                sCon.getHargaSeat(t.getNomorSeat(), t.getdetailPerjalanan().getDetailPerjalanId())
            });
        }
//        
//        
        idPemesanLbl.setText(Integer.toString(p.getTransaksiId()));
        namaPemesanLbl.setText(m.getNama());
        emailPemesanLbl.setText(m.getEmail());
        saldoLbl.setText(Double.toString(m.getTwallet().getSaldo()));
        totalHargaLbl.setText(Double.toString(p.getTotalTagihan()));
        biayaAdminLbl.setText(Double.toString(p.getJumlahPesanan()*2500));
        pajakLbl.setText(Double.toString(p.getTotalTagihan() * 0.1));
        
        double total = p.getTotalTagihan() + (p.getJumlahPesanan()*2500)+ (p.getTotalTagihan()*0.1);
        subTotalLbl.setText(Double.toString(total));
        
        findPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try{
                    NotEnoughMoneyException();
                    if(total <= m.getTwallet().getSaldo()){
                        tCon.updateStatusPemesanan(p.getTransaksiId(),"Sudah Bayar");
                        twCon.kredit(m.getTwallet().getTWalletID(),total);
                        setForm(new SuccessPaymentPanel(m));
                    }else{
                        
                    }    
                }catch(NotEnoughMoneyException e2){
                    JOptionPane.showMessageDialog(paymentPanel,"Uang Anda tidak cukup!");
                }catch(Exception e1){
                    System.out.println(e1.getMessage());
                }    
                   
            }
        });
        
        depositLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setForm(new DepositPanel(m));   
            }
        });
        
        depositLogo.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setForm(new DepositPanel(m));   
            }
        });
        
    }

    private void setForm(JComponent com){
        mainPanel.removeAll();
        mainPanel.setLayout(new CardLayout());
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void init(){
        
        JPanel panel = new JPanel();
        panel.setBackground(Color.WHITE);
       
        sp.setVerticalScrollBar(new ScrollBar.ScrollBarCustom());
        sp.getVerticalScrollBar().setBackground(Color.WHITE);
        sp.setCorner(JScrollPane.UPPER_RIGHT_CORNER, panel);
        sp.getViewport().setBackground(Color.WHITE);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new Panel.PanelBorder();
        idPemesanLbl = new javax.swing.JLabel();
        namaPemesanLbl = new javax.swing.JLabel();
        emailPemesanLbl = new javax.swing.JLabel();
        sp = new javax.swing.JScrollPane();
        tablePenumpang = new Table.Table();
        panelKecil = new javax.swing.JPanel();
        biayaTagihanLbl = new javax.swing.JLabel();
        nomorIdPemesanLbl = new javax.swing.JLabel();
        dataPemesanLbl = new javax.swing.JLabel();
        namaTextPemesan = new javax.swing.JLabel();
        emailTextLbl = new javax.swing.JLabel();
        dataPenumpangLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        biayaAdminTextLbl = new javax.swing.JLabel();
        totalHargaTextLbl = new javax.swing.JLabel();
        pajakTextLbl = new javax.swing.JLabel();
        rpLbl = new javax.swing.JLabel();
        totalHargaLbl = new javax.swing.JLabel();
        subTotalTextLbl = new javax.swing.JLabel();
        rpLbl4 = new javax.swing.JLabel();
        rpLbl3 = new javax.swing.JLabel();
        rpLbl2 = new javax.swing.JLabel();
        subTotalLbl = new javax.swing.JLabel();
        biayaAdminLbl = new javax.swing.JLabel();
        pajakLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        findPanel1 = new Panel.PanelBorder();
        bayarLbl1 = new javax.swing.JLabel();
        panelBorder2 = new Panel.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        saldoLbl = new javax.swing.JLabel();
        depositLogo = new javax.swing.JLabel();
        depositLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(244, 244, 244));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        idPemesanLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idPemesanLbl.setForeground(new java.awt.Color(0, 0, 0));
        idPemesanLbl.setText("ID Pemesanan");

        namaPemesanLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        namaPemesanLbl.setForeground(new java.awt.Color(0, 0, 0));
        namaPemesanLbl.setText("Nama Pemesan");

        emailPemesanLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailPemesanLbl.setForeground(new java.awt.Color(0, 0, 0));
        emailPemesanLbl.setText("Email Pemesan");

        tablePenumpang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Jenis Seat", "Nomor Seat", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sp.setViewportView(tablePenumpang);

        panelKecil.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout panelKecilLayout = new javax.swing.GroupLayout(panelKecil);
        panelKecil.setLayout(panelKecilLayout);
        panelKecilLayout.setHorizontalGroup(
            panelKecilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        panelKecilLayout.setVerticalGroup(
            panelKecilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        biayaTagihanLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        biayaTagihanLbl.setForeground(new java.awt.Color(0, 0, 0));
        biayaTagihanLbl.setText("Biaya Tagihan");

        nomorIdPemesanLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomorIdPemesanLbl.setForeground(new java.awt.Color(0, 0, 0));
        nomorIdPemesanLbl.setText("Nomor :");

        dataPemesanLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dataPemesanLbl.setForeground(new java.awt.Color(0, 0, 0));
        dataPemesanLbl.setText("Data Pemesan");

        namaTextPemesan.setForeground(new java.awt.Color(0, 0, 0));
        namaTextPemesan.setText("Nama : ");

        emailTextLbl.setForeground(new java.awt.Color(0, 0, 0));
        emailTextLbl.setText("Email  : ");

        dataPenumpangLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dataPenumpangLbl.setForeground(new java.awt.Color(0, 0, 0));
        dataPenumpangLbl.setText("Data Penumpang");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        biayaAdminTextLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        biayaAdminTextLbl.setForeground(new java.awt.Color(0, 0, 0));
        biayaAdminTextLbl.setText("Biaya Admin");

        totalHargaTextLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalHargaTextLbl.setForeground(new java.awt.Color(0, 0, 0));
        totalHargaTextLbl.setText("Total Harga");

        pajakTextLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pajakTextLbl.setForeground(new java.awt.Color(0, 0, 0));
        pajakTextLbl.setText("Pajak");

        rpLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rpLbl.setForeground(new java.awt.Color(0, 0, 0));
        rpLbl.setText("Rp");

        totalHargaLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalHargaLbl.setForeground(new java.awt.Color(0, 0, 0));
        totalHargaLbl.setText("Harga");

        subTotalTextLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subTotalTextLbl.setForeground(new java.awt.Color(0, 0, 0));
        subTotalTextLbl.setText("Sub Total");

        rpLbl4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rpLbl4.setForeground(new java.awt.Color(0, 0, 0));
        rpLbl4.setText("Rp");

        rpLbl3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rpLbl3.setForeground(new java.awt.Color(0, 0, 0));
        rpLbl3.setText("Rp");

        rpLbl2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rpLbl2.setForeground(new java.awt.Color(0, 0, 0));
        rpLbl2.setText("Rp");

        subTotalLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subTotalLbl.setForeground(new java.awt.Color(0, 0, 0));
        subTotalLbl.setText("Harga");

        biayaAdminLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        biayaAdminLbl.setForeground(new java.awt.Color(0, 0, 0));
        biayaAdminLbl.setText("Harga");

        pajakLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pajakLbl.setForeground(new java.awt.Color(0, 0, 0));
        pajakLbl.setText("Harga");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        findPanel1.setBackground(new java.awt.Color(0, 153, 153));
        findPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        findPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                findPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                findPanel1MouseExited(evt);
            }
        });

        bayarLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bayarLbl1.setForeground(new java.awt.Color(255, 255, 255));
        bayarLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bayarLbl1.setText("Pay");

        javax.swing.GroupLayout findPanel1Layout = new javax.swing.GroupLayout(findPanel1);
        findPanel1.setLayout(findPanel1Layout);
        findPanel1Layout.setHorizontalGroup(
            findPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(bayarLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        findPanel1Layout.setVerticalGroup(
            findPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bayarLbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(totalHargaLbl)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(findPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(subTotalTextLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rpLbl4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subTotalLbl)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalHargaTextLbl)
                                    .addComponent(biayaAdminTextLbl)
                                    .addComponent(pajakTextLbl))
                                .addGap(82, 82, 82)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rpLbl)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rpLbl2)
                                            .addComponent(rpLbl3))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(biayaAdminLbl))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(pajakLbl)))))))))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalHargaTextLbl)
                    .addComponent(rpLbl)
                    .addComponent(totalHargaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(biayaAdminTextLbl)
                            .addComponent(rpLbl2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(biayaAdminLbl)
                        .addGap(11, 11, 11)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pajakTextLbl)
                    .addComponent(rpLbl3)
                    .addComponent(pajakLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTotalTextLbl)
                    .addComponent(rpLbl4)
                    .addComponent(subTotalLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(findPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelBorder2.setBackground(new java.awt.Color(25, 135, 185));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("T-Wallet");

        saldoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saldoLbl.setForeground(new java.awt.Color(255, 255, 255));
        saldoLbl.setText("Saldo Pemesan");

        depositLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Deposit.png"))); // NOI18N
        depositLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositLogoMouseExited(evt);
            }
        });

        depositLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        depositLbl.setForeground(new java.awt.Color(255, 255, 255));
        depositLbl.setText("+ Deposit");
        depositLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoLbl)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(depositLogo)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(depositLbl)
                .addGap(28, 28, 28))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saldoLbl))
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(depositLogo)
                        .addGap(2, 2, 2)
                        .addComponent(depositLbl)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(panelKecil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(biayaTagihanLbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataPenumpangLbl)
                            .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(nomorIdPemesanLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idPemesanLbl)
                                    .addGap(377, 377, 377)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addComponent(emailTextLbl)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(emailPemesanLbl))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addComponent(namaTextPemesan)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(namaPemesanLbl))
                                        .addComponent(dataPemesanLbl))
                                    .addGap(50, 50, 50))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                    .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 60, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKecil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(biayaTagihanLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(dataPemesanLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(namaPemesanLbl)
                                    .addComponent(namaTextPemesan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailPemesanLbl)
                                    .addComponent(emailTextLbl)))
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idPemesanLbl)
                                .addComponent(nomorIdPemesanLbl)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataPenumpangLbl)
                .addGap(18, 18, 18)
                .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void findPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPanel1MouseEntered
        findPanel1.setBackground(new Color(0,102,102));
        findPanel1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_findPanel1MouseEntered

    private void findPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPanel1MouseExited
        findPanel1.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_findPanel1MouseExited

    private void depositLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositLogoMouseEntered
        depositLogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_depositLogoMouseEntered

    private void depositLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositLogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_depositLogoMouseClicked

    private void depositLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositLogoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_depositLogoMouseExited

    private void depositLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositLblMouseEntered
        depositLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_depositLblMouseEntered

    private void depositLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositLblMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_depositLblMouseExited

    private void depositLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_depositLblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bayarLbl1;
    private javax.swing.JLabel biayaAdminLbl;
    private javax.swing.JLabel biayaAdminTextLbl;
    private javax.swing.JLabel biayaTagihanLbl;
    private javax.swing.JLabel dataPemesanLbl;
    private javax.swing.JLabel dataPenumpangLbl;
    private javax.swing.JLabel depositLbl;
    private javax.swing.JLabel depositLogo;
    private javax.swing.JLabel emailPemesanLbl;
    private javax.swing.JLabel emailTextLbl;
    private Panel.PanelBorder findPanel1;
    private javax.swing.JLabel idPemesanLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private Panel.PanelBorder mainPanel;
    private javax.swing.JLabel namaPemesanLbl;
    private javax.swing.JLabel namaTextPemesan;
    private javax.swing.JLabel nomorIdPemesanLbl;
    private javax.swing.JLabel pajakLbl;
    private javax.swing.JLabel pajakTextLbl;
    private Panel.PanelBorder panelBorder2;
    private javax.swing.JPanel panelKecil;
    private javax.swing.JLabel rpLbl;
    private javax.swing.JLabel rpLbl2;
    private javax.swing.JLabel rpLbl3;
    private javax.swing.JLabel rpLbl4;
    private javax.swing.JLabel saldoLbl;
    private javax.swing.JScrollPane sp;
    private javax.swing.JLabel subTotalLbl;
    private javax.swing.JLabel subTotalTextLbl;
    private Table.Table tablePenumpang;
    private javax.swing.JLabel totalHargaLbl;
    private javax.swing.JLabel totalHargaTextLbl;
    // End of variables declaration//GEN-END:variables
}
