/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import Model.Member;
import com.sun.source.tree.WildcardTree;
import java.awt.CardLayout;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;

/**
 *
 * @author USER
 */
public class TWalletPanel extends javax.swing.JPanel {

    private Member member;
    
    public void setMember(Member member){
        saldoLbl.setText(Double.toString(member.getTwallet().getSaldo()));
        this.member = member;
    }
    
    public TWalletPanel(Member member) {
        initComponents();
        setMember(member);
        
         depoIcon.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setForm(new DepositPanel(member));
            }
         });
         
        depoLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setForm(new DepositPanel(member));
            }
         });
        
        depoPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setForm(new DepositPanel(member));
            }
         });
        
        
        withdrawIcon.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setForm(new WithdrawPanel(member));
            }
         });
          
        
        withdrawLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setForm(new WithdrawPanel(member));
            }
         });
        
        withdrawPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setForm(new WithdrawPanel(member));
            }
         }); 
    }
    
    
    private void setForm(JComponent com){
        mainPanel.removeAll();
        mainPanel.setLayout(new CardLayout());
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        depoWithPanel = new Panel.PanelBorder();
        garisPanel = new javax.swing.JPanel();
        depoPanel = new javax.swing.JPanel();
        depoIcon = new javax.swing.JLabel();
        depoLbl = new javax.swing.JLabel();
        withdrawPanel = new javax.swing.JPanel();
        withdrawIcon = new javax.swing.JLabel();
        withdrawLbl = new javax.swing.JLabel();
        saldoPanel = new javax.swing.JPanel();
        rpLbl = new javax.swing.JLabel();
        saldoLbl = new javax.swing.JLabel();
        moneyIcon = new javax.swing.JLabel();
        panelBorder1 = new Panel.PanelBorder();
        userLbl = new javax.swing.JLabel();
        logoLbl = new javax.swing.JLabel();
        tiketaLBl = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        depoWithPanel.setBackground(new java.awt.Color(0, 91, 110));

        garisPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout garisPanelLayout = new javax.swing.GroupLayout(garisPanel);
        garisPanel.setLayout(garisPanelLayout);
        garisPanelLayout.setHorizontalGroup(
            garisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        garisPanelLayout.setVerticalGroup(
            garisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        depoPanel.setBackground(new java.awt.Color(0, 91, 110));
        depoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depoPanelMouseEntered(evt);
            }
        });

        depoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Deposit.png"))); // NOI18N
        depoIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depoIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depoIconMouseEntered(evt);
            }
        });

        depoLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        depoLbl.setForeground(new java.awt.Color(255, 255, 255));
        depoLbl.setText("Deposit");
        depoLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depoLblMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout depoPanelLayout = new javax.swing.GroupLayout(depoPanel);
        depoPanel.setLayout(depoPanelLayout);
        depoPanelLayout.setHorizontalGroup(
            depoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depoPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(depoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depoPanelLayout.createSequentialGroup()
                        .addComponent(depoIcon)
                        .addGap(3, 3, 3))
                    .addGroup(depoPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(depoLbl)))
                .addGap(22, 22, 22))
        );
        depoPanelLayout.setVerticalGroup(
            depoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depoIcon)
                .addGap(1, 1, 1)
                .addComponent(depoLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        withdrawPanel.setBackground(new java.awt.Color(0, 91, 110));
        withdrawPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawPanelMouseEntered(evt);
            }
        });

        withdrawIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Withdraw.png"))); // NOI18N
        withdrawIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawIconMouseEntered(evt);
            }
        });

        withdrawLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        withdrawLbl.setForeground(new java.awt.Color(255, 255, 255));
        withdrawLbl.setText("Withdraw");
        withdrawLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawLblMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout withdrawPanelLayout = new javax.swing.GroupLayout(withdrawPanel);
        withdrawPanel.setLayout(withdrawPanelLayout);
        withdrawPanelLayout.setHorizontalGroup(
            withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(withdrawIcon))
                    .addComponent(withdrawLbl))
                .addGap(14, 14, 14))
        );
        withdrawPanelLayout.setVerticalGroup(
            withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(withdrawIcon)
                .addGap(1, 1, 1)
                .addComponent(withdrawLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout depoWithPanelLayout = new javax.swing.GroupLayout(depoWithPanel);
        depoWithPanel.setLayout(depoWithPanelLayout);
        depoWithPanelLayout.setHorizontalGroup(
            depoWithPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depoWithPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(depoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(garisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(withdrawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        depoWithPanelLayout.setVerticalGroup(
            depoWithPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depoWithPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depoWithPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdrawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(garisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saldoPanel.setBackground(new java.awt.Color(255, 255, 255));

        rpLbl.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        rpLbl.setForeground(new java.awt.Color(0, 0, 0));
        rpLbl.setText("Rp");

        saldoLbl.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        saldoLbl.setForeground(new java.awt.Color(0, 0, 0));
        saldoLbl.setText("Saldo Anda");

        moneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Money.png"))); // NOI18N

        javax.swing.GroupLayout saldoPanelLayout = new javax.swing.GroupLayout(saldoPanel);
        saldoPanel.setLayout(saldoPanelLayout);
        saldoPanelLayout.setHorizontalGroup(
            saldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saldoPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(moneyIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rpLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldoLbl)
                .addGap(96, 96, 96))
        );
        saldoPanelLayout.setVerticalGroup(
            saldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saldoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(moneyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(saldoPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(saldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoLbl)
                    .addComponent(rpLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorder1.setBackground(new java.awt.Color(0, 91, 110));

        userLbl.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        userLbl.setForeground(new java.awt.Color(255, 255, 255));
        userLbl.setText("User");

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User Icon.png"))); // NOI18N

        tiketaLBl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tiketaLBl.setForeground(new java.awt.Color(255, 255, 255));
        tiketaLBl.setText("TIKETA WALLET");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiketaLBl)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(logoLbl))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(userLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(tiketaLBl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLbl)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(saldoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(depoWithPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 273, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(saldoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(depoWithPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void depoIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depoIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_depoIconMouseClicked

    private void depoIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depoIconMouseEntered
        depoIcon.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_depoIconMouseEntered

    private void depoLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depoLblMouseEntered
        depoLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_depoLblMouseEntered

    private void depoPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depoPanelMouseEntered
        depoPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_depoPanelMouseEntered

    private void withdrawIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawIconMouseEntered
        withdrawIcon.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_withdrawIconMouseEntered

    private void withdrawLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawLblMouseEntered
        withdrawLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_withdrawLblMouseEntered

    private void withdrawPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawPanelMouseEntered
        withdrawPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_withdrawPanelMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel depoIcon;
    private javax.swing.JLabel depoLbl;
    private javax.swing.JPanel depoPanel;
    private Panel.PanelBorder depoWithPanel;
    private javax.swing.JPanel garisPanel;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JLabel moneyIcon;
    private Panel.PanelBorder panelBorder1;
    private javax.swing.JLabel rpLbl;
    private javax.swing.JLabel saldoLbl;
    private javax.swing.JPanel saldoPanel;
    private javax.swing.JLabel tiketaLBl;
    private javax.swing.JLabel userLbl;
    private javax.swing.JLabel withdrawIcon;
    private javax.swing.JLabel withdrawLbl;
    private javax.swing.JPanel withdrawPanel;
    // End of variables declaration//GEN-END:variables
}
