/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import Exception.NotEnoughMoneyException;
import Model.Member;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class WithdrawPanel extends javax.swing.JPanel {

    private Member member;
    
    public void setMember(Member member){
        saldoLbl.setText(Double.toString(member.getTwallet().getSaldo()));
        this.member = member;
    }
    
    public void NotEnoughMoneyException() throws NotEnoughMoneyException{
        if(Double.parseDouble(jmlWithInput.getText()) > member.getTwallet().getSaldo()){
            throw new NotEnoughMoneyException("Uang tidak Cukup!");
        }
    }
    
    
    public WithdrawPanel(Member member) {
        JPanel WithdrawPanel = new JPanel();
        initComponents();
        setMember(member);
        String action = "withdraw";

            sendBtn.addMouseListener(new MouseAdapter() {
                    @Override                
                    public void mouseClicked(MouseEvent e) {
                         try{
                            NotEnoughMoneyException();
                            if(Double.parseDouble(jmlWithInput.getText()) > member.getTwallet().getSaldo()){
                                JOptionPane.showMessageDialog(mainPanel, "Jumlah Withdrawal Melebihi Jumlah Saldo!!!");
                            }else if (Double.parseDouble(jmlWithInput.getText()) < 10000){
                                JOptionPane.showMessageDialog(mainPanel, "Jumlah Withdrawal Minimal Rp.10.000,- !!!");
                            }else{
                                setForm(new SuccessPaymentPanel(member,action,Double.parseDouble(jmlWithInput.getText())));

                            }
                        }catch(NotEnoughMoneyException e2){
                            JOptionPane.showMessageDialog(WithdrawPanel,"Uang Anda tidak cukup!");
                        }
                    }
                });
    }
    
    private void setForm(JComponent com){
        mainPanel.removeAll();
        mainPanel.setLayout(new CardLayout());
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        withdrawLbl = new javax.swing.JLabel();
        jmlWithInput = new javax.swing.JTextField();
        metodLbl = new javax.swing.JLabel();
        metodComboBox = new javax.swing.JComboBox<>();
        sendBtn = new rojerusan.RSMaterialButtonRectangle();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saldoLbl = new javax.swing.JLabel();
        rpLbl = new javax.swing.JLabel();
        moneyIcon = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        withdrawLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        withdrawLbl.setForeground(new java.awt.Color(0, 0, 0));
        withdrawLbl.setText("Masukkan Jumlah Withdraw");

        jmlWithInput.setBackground(new java.awt.Color(255, 255, 255, 80));
        jmlWithInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jmlWithInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmlWithInputMouseEntered(evt);
            }
        });
        jmlWithInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlWithInputActionPerformed(evt);
            }
        });

        metodLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        metodLbl.setForeground(new java.awt.Color(0, 0, 0));
        metodLbl.setText("Pilih Tujuan Transfer");

        metodComboBox.setBackground(new java.awt.Color(255, 255, 255));
        metodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dana", "Ovo", "Gopay", "BCA", "BRI", "Mandiri" }));

        sendBtn.setText("Send");
        sendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendBtnMouseEntered(evt);
            }
        });
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 91, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/WdPanel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        saldoLbl.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        saldoLbl.setForeground(new java.awt.Color(0, 0, 0));
        saldoLbl.setText("Saldo Anda");

        rpLbl.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        rpLbl.setForeground(new java.awt.Color(0, 0, 0));
        rpLbl.setText("Rp");

        moneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Money.png"))); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(withdrawLbl)
                            .addComponent(jmlWithInput, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(metodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(metodLbl)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(moneyIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rpLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saldoLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoLbl)
                            .addComponent(rpLbl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(withdrawLbl)
                .addGap(18, 18, 18)
                .addComponent(jmlWithInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(metodLbl)
                .addGap(18, 18, 18)
                .addComponent(metodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jmlWithInputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmlWithInputMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlWithInputMouseEntered

    private void jmlWithInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlWithInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlWithInputActionPerformed

    private void sendBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBtnMouseClicked

    }//GEN-LAST:event_sendBtnMouseClicked

    private void sendBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sendBtnMouseEntered

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed

    }//GEN-LAST:event_sendBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jmlWithInput;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> metodComboBox;
    private javax.swing.JLabel metodLbl;
    private javax.swing.JLabel moneyIcon;
    private javax.swing.JLabel rpLbl;
    private javax.swing.JLabel saldoLbl;
    private rojerusan.RSMaterialButtonRectangle sendBtn;
    private javax.swing.JLabel withdrawLbl;
    // End of variables declaration//GEN-END:variables
}
