/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Exception.ConfirmPasswordException;
import Exception.InputKosongException;
import Model.Member;
import Model.TWallet;
import Control.MemberControl;
import Control.TWalletControl;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class SignUpView extends javax.swing.JFrame {
 private MemberControl memberControl;
 private TWalletControl twalletControl; 
    
    public SignUpView() {
        initComponents();
        memberControl = new MemberControl();
        twalletControl = new TWalletControl();
        // Mengatur form berada di tengah (center)
        setLocationRelativeTo(null);
        setVisible(true);
        buttonGroup1.clearSelection();
    }
    
    public void InputKosongException() throws InputKosongException{
        if(!maleRadioBtn.isSelected() && !femaleRadioBtn.isSelected() || fullNameInput.getText().isBlank() || usernameInput.getText().isBlank() || passwordInput.getText().isBlank() || confirmPasswordInput.getText().isBlank() || emailInput.getText().isBlank() || idNumberInput.getText().isBlank() || phoneNumberInput.getText().isBlank()){
            throw new InputKosongException("Input User Tidak Boleh Kosong!");
        }
    }
    
    public void ConfirmPasswordException() throws ConfirmPasswordException{
        if(!passwordInput.getText().equals(confirmPasswordInput.getText())){
            throw new ConfirmPasswordException("Salah konfirmasi password!");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dasarPanel = new javax.swing.JPanel();
        imageLbl = new javax.swing.JLabel();
        signUpLbl = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        usernameLbl = new javax.swing.JLabel();
        createAccountBtn = new rojerusan.RSMaterialButtonRectangle();
        alreadyHaveAccountLbl = new javax.swing.JLabel();
        loginLbl = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        passwordLbl = new javax.swing.JLabel();
        fullNameLbl = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        confirmPasswordLbl = new javax.swing.JLabel();
        fullNameInput = new javax.swing.JTextField();
        confirmPasswordInput = new javax.swing.JPasswordField();
        genderLbl = new javax.swing.JLabel();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        idNumberInput = new javax.swing.JTextField();
        idNumberLbl = new javax.swing.JLabel();
        phoneNumberInput = new javax.swing.JTextField();
        phoneNumberLbl = new javax.swing.JLabel();
        captchaLbl = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        dasarPanel.setBackground(new java.awt.Color(255, 255, 255));

        imageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/SignUpImage.png"))); // NOI18N

        signUpLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        signUpLbl.setText("Sign Up");

        usernameInput.setBackground(new java.awt.Color(255, 255, 255, 80));
        usernameInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });

        usernameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usernameLbl.setText("Username");

        createAccountBtn.setText("Create Account");
        createAccountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountBtnMouseClicked(evt);
            }
        });
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });

        alreadyHaveAccountLbl.setForeground(new java.awt.Color(0, 0, 0));
        alreadyHaveAccountLbl.setText("Already have an account?");

        loginLbl.setForeground(new java.awt.Color(0, 204, 204));
        loginLbl.setText("Log In");
        loginLbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loginLblMouseMoved(evt);
            }
        });
        loginLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginLblMouseExited(evt);
            }
        });

        passwordInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        passwordLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passwordLbl.setText("Password");

        fullNameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fullNameLbl.setText("Full Name");

        emailInput.setBackground(new java.awt.Color(255, 255, 255, 80));
        emailInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });

        emailLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailLbl.setText("Email Address");

        confirmPasswordLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confirmPasswordLbl.setText("Confirm Password");

        fullNameInput.setBackground(new java.awt.Color(255, 255, 255, 80));
        fullNameInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        fullNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameInputActionPerformed(evt);
            }
        });

        confirmPasswordInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        genderLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genderLbl.setText("Gender");

        buttonGroup1.add(maleRadioBtn);
        maleRadioBtn.setText("Male");
        maleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(femaleRadioBtn);
        femaleRadioBtn.setText("Female");
        femaleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioBtnActionPerformed(evt);
            }
        });

        idNumberInput.setBackground(new java.awt.Color(255, 255, 255, 80));
        idNumberInput.setText("13 Number");
        idNumberInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        idNumberInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idNumberInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idNumberInputFocusLost(evt);
            }
        });
        idNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNumberInputActionPerformed(evt);
            }
        });

        idNumberLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idNumberLbl.setText("ID Number");

        phoneNumberInput.setBackground(new java.awt.Color(255, 255, 255, 80));
        phoneNumberInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        phoneNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberInputActionPerformed(evt);
            }
        });

        phoneNumberLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phoneNumberLbl.setText("Phone Number");

        captchaLbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        captchaLbl.setForeground(new java.awt.Color(0, 0, 0));
        captchaLbl.setText("This site is protected by reCAPTCHA and the Google");

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 102, 255));
        lbl1.setText("Privacy Policy");

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("and");

        lbl3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 102, 255));
        lbl3.setText("Terms of Service");

        lbl4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 0, 0));
        lbl4.setText("apply");

        javax.swing.GroupLayout dasarPanelLayout = new javax.swing.GroupLayout(dasarPanel);
        dasarPanel.setLayout(dasarPanelLayout);
        dasarPanelLayout.setHorizontalGroup(
            dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarPanelLayout.createSequentialGroup()
                .addComponent(imageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dasarPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dasarPanelLayout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fullNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dasarPanelLayout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addGroup(dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmPasswordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fullNameInput, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(genderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dasarPanelLayout.createSequentialGroup()
                                .addComponent(maleRadioBtn)
                                .addGap(18, 18, 18)
                                .addComponent(femaleRadioBtn))
                            .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(captchaLbl)
                            .addGroup(dasarPanelLayout.createSequentialGroup()
                                .addComponent(lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl4)))
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarPanelLayout.createSequentialGroup()
                                .addComponent(alreadyHaveAccountLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarPanelLayout.createSequentialGroup()
                                .addComponent(signUpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(288, 288, 288))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarPanelLayout.createSequentialGroup()
                                .addComponent(createAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(219, 219, 219))))))
        );
        dasarPanelLayout.setVerticalGroup(
            dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dasarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alreadyHaveAccountLbl)
                    .addComponent(loginLbl))
                .addGap(7, 7, 7)
                .addComponent(signUpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dasarPanelLayout.createSequentialGroup()
                        .addComponent(fullNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fullNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dasarPanelLayout.createSequentialGroup()
                        .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmPasswordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(confirmPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(genderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRadioBtn)
                    .addComponent(femaleRadioBtn))
                .addGap(18, 18, 18)
                .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(idNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phoneNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(phoneNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(captchaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dasarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lbl2)
                    .addComponent(lbl3)
                    .addComponent(lbl4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dasarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dasarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameInputActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void loginLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLblMouseExited
                loginLbl.setForeground(new Color(0,204,204));
                loginLbl.setFont(new Font("Tahoma", Font.PLAIN, 12));
                loginLbl.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_loginLblMouseExited

    private void loginLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLblMouseEntered
                loginLbl.setForeground(new Color(0,102,204));
                loginLbl.setFont(new Font("Tahoma", Font.BOLD, 13));
                loginLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
                Font originalFont = loginLbl.getFont();
                Map<TextAttribute, Object> attributes = new HashMap<>();
                attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
                attributes.put(TextAttribute.FONT, originalFont.deriveFont(Font.BOLD));
        
                loginLbl.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_loginLblMouseEntered

    private void loginLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLblMouseClicked
        LoginView lv = new LoginView();
        this.dispose ();
        lv.setVisible(true);
    }//GEN-LAST:event_loginLblMouseClicked

    private void loginLblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLblMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_loginLblMouseMoved

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
         try{
            Long.parseLong(phoneNumberInput.getText());
            Long.parseLong(idNumberInput.getText());
            boolean check = memberControl.isAccountExists(usernameInput.getText(), passwordInput.getText());
            if(check == true){
                JOptionPane.showMessageDialog(this, "Username dan Password sudah ada!"); 
            }else{
                
            ConfirmPasswordException();
            InputKosongException();
            TWallet TW = new TWallet(0);
            twalletControl.insertTWallet(TW);
            
            
            if(maleRadioBtn.isSelected()){
                Member M = new Member(fullNameInput.getText(),emailInput.getText(),phoneNumberInput.getText(),"Male",usernameInput.getText(),passwordInput.getText(),TW);
                memberControl.insertMember(M);
                
            }else if(femaleRadioBtn.isSelected()){
                Member M = new Member(fullNameInput.getText(),emailInput.getText(),phoneNumberInput.getText(),"Female",usernameInput.getText(),passwordInput.getText(),TW);
                memberControl.insertMember(M);
            }
            
            }
            
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, "Input User Tidak Boleh Kosong!");
        }catch(ConfirmPasswordException e){
            JOptionPane.showMessageDialog(this, "Salah konfirmasi password!");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Nomor KTP dan Phone Number Harus Angka Semua!!");
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_createAccountBtnActionPerformed

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void idNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNumberInputActionPerformed

    private void phoneNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberInputActionPerformed

    private void idNumberInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idNumberInputFocusGained
        String temp = idNumberInput.getText();
        
        if(temp.equals("13 Number")){
            idNumberInput.setText("");
        }
    }//GEN-LAST:event_idNumberInputFocusGained

    private void idNumberInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idNumberInputFocusLost
        String temp = idNumberInput.getText();
        
        if(temp.equals("") || temp.equals("13 Number")){
            idNumberInput.setText("13 Number");
        }
    }//GEN-LAST:event_idNumberInputFocusLost

    private void createAccountBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountBtnMouseClicked
        LoginView lv = new LoginView();
        this.dispose ();
        lv.setVisible(true);
    }//GEN-LAST:event_createAccountBtnMouseClicked

    private void maleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioBtnActionPerformed
        // TODO add your handling code here:
//        if(maleRadioBtn.isSelected()){
//            femaleRadioBtn.setEnabled(false);
//        }else if(!maleRadioBtn.isSelected()){
//            femaleRadioBtn.setEnabled(true);
//        }
    }//GEN-LAST:event_maleRadioBtnActionPerformed

    private void femaleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioBtnActionPerformed
        // TODO add your handling code here:
//        if(femaleRadioBtn.isSelected()){
//            maleRadioBtn.setEnabled(false);
//        }else if(!femaleRadioBtn.isSelected()){
//            maleRadioBtn.setEnabled(true);
//        }
    }//GEN-LAST:event_femaleRadioBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alreadyHaveAccountLbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel captchaLbl;
    private javax.swing.JPasswordField confirmPasswordInput;
    private javax.swing.JLabel confirmPasswordLbl;
    private rojerusan.RSMaterialButtonRectangle createAccountBtn;
    private javax.swing.JPanel dasarPanel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JTextField fullNameInput;
    private javax.swing.JLabel fullNameLbl;
    private javax.swing.JLabel genderLbl;
    private javax.swing.JTextField idNumberInput;
    private javax.swing.JLabel idNumberLbl;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField phoneNumberInput;
    private javax.swing.JLabel phoneNumberLbl;
    private javax.swing.JLabel signUpLbl;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
